### ISSUE TITLE
Serializer produced wrong sql statement when using .group(by:) and .sort(_:) together.

### ISSUE THREAD

**Issue by IsaacXen** [vapor/sql#2]
Serializer produced wrong sql statement when using .group(by:) and .sort(_:) together.

### Steps to reproduce

    SomeModel.query(on: req)
        .group(by: \.id)
        .sort(\.id)
        .all()

### Expected behavior

    SELECT * FROM `some_model`
    GROUP BY `some_model`.`id`
    ORDER BY `some_model`.`id`;

`GROUP BY` before `ORDER BY`.

### Actual behavior

    SELECT * FROM `some_model`
    ORDER BY `some_model`.`id`
    GROUP BY `some_model`.`id`;

`ORDER BY` before `GROUP BY`.

**Comment by rafiki270** [comment]
@IsaacXen thanks, fixed in https://github.com/vapor/sql/pull/5
