### ISSUE TITLE
new name

### ISSUE THREAD

**Issue by tanner0101** [vapor/sql#28]
We should give this package a more unique name, like "Fluent".

- Ink
- Graphite
- SWQL
- Slinq
- Core
- Kit
- Star

**Comment by mcdappdev** [comment]
Maybe something with the word "structure" or "structured?"

**Comment by calebkleveter** [comment]
Jet is a material that the term 'jet black' came from. Ink is often black.

**Comment by tanner0101** [comment]
I like `Jet` quite a bit, but would reverse the names:
```swift
import JetSQLite
```

**Comment by grundoon** [comment]
Surprised you're not sticking within the domain 😉  – boost, coil, deck, juice, kick... draw, wick, atomizer, liquid... probably missed some.

**Comment by tanner0101** [comment]
What about `Star`? Alluding to `SELECT *` commonly being read as "Select star". 

```swift
import Star
```

```swift
import StarSQLite
import StarPostgreSQL
import StarMySQL
```

**Comment by mcdappdev** [comment]
I’m a fan. I also like that it sticks to the Vapor naming domain of earth-y things

**Comment by joscdk** [comment]
Star could be nice :)

**Comment by calebkleveter** [comment]
What about 'Fume'. It's synonymous with Vapor.

**Comment by rafiki270** [comment]
tbh I think we should have just driver (low level) and fluent (high level) to make it clear for everyone and to abide with the naming rules ... most people will be using FluentSQLite (etc ...) anyways without looking into the underlaying packages ... as for this one specifically, I would leave it as it is. Current name is most descriptive for the people who may wander into it's codebase

**Comment by calebkleveter** [comment]
@rafiki270 This is why we are looking into a new name: https://github.com/vapor/sqlite/issues/47. So `vapor/sql` might be able to stay, but what we really need are new names for the `sqlite`, `mysql`, and `postgresql` repos.

**Comment by rafiki270** [comment]
that's why I suggest to go back to driver for the ones you have mentioned and leave as sql as is

**Comment by vzsg** [comment]
Call me boring but I agree with @rafiki270, adding a fantasy name doesn't really add value, only noise.

**Comment by MartinLasek** [comment]
Like `SQLiteDriver`, `MySQLDriver` and `PostgreSQLDriver` ?

**Comment by rafiki270** [comment]
yep

**Comment by tanner0101** [comment]
> Call me boring but I agree with @rafiki270, adding a fantasy name doesn't really add value, only noise.

I agree, but we need something unique to prefix the SQLite driver because we can't use just SQLite. Something like `vapor/vapor-sqlite` is even more misleading. 

> I like the Star but would that mean that the Provider Packages would then be named FluentStarMySQL 😄 ?

No, that would stay `FluentMySQL`. The hierarchy would be like so:

`libsqlite`: Root library
`NIOSQLite`: combine `NIO` event loops + `libsqlite` in Swifty API
`StarSQLite`: combine `Star` (low level SQL orm) with `NIOSQLite`
`FluentSQLite`: combine `StarSQLite` with `Fluent`

**Comment by tanner0101** [comment]
![screen shot 2018-08-07 at 7 03 39 pm](https://user-images.githubusercontent.com/1342803/43807123-fb157d5a-9a74-11e8-9296-cb42e296dad5.png)

**Comment by clayellis** [comment]
For those that missed the party in Discord (and lesson on gravitational systems by @gwynne), there's a consensus building around this:

![image](https://user-images.githubusercontent.com/10712068/43807882-99a6d33c-9a67-11e8-9cb0-235cd47892fe.png)

**Comment by vzsg** [comment]
I just browsed USPTO's Trademark Database, and "SQL" is not a registered trademark (unlike the products MySQL, PostgreSQL etc.), so I still don't think renaming vapor/sql is necessary.

**Comment by clayellis** [comment]
Regardless, I think since the "children" (the integration packages) need a renaming, it would be nice for the "parent" (`sql`) to be the source of that monicker. (Children inheriting names from their parents... seems kinda poetic.) It sort of ties the whole hierarchy together — in the above trees, the children always get a mixed name from their parents, with the "monicker" (NIO, Core/Kit, Fluent) coming from the right side.

**Comment by tanner0101** [comment]
To expand on what @clayellis said, if we leave `vapor/sql` as just `SQL`, then we don't really have anything useful to name the integration packages. Following the pattern, the name would be `import SQLSQLite` which is awful.

**Comment by vzsg** [comment]
I might be missing something, do those "integration packages" actually exist, or is there anything that warrants their future existence? Right now, it seems the SQL classes are interwoven in MySQL, for example...

So why not keep it simple:

|Old|New|
|-|-|
|SQL|SQL|
|Fluent|Fluent|
|MySQL|MySQLDriver|
|PostgreSQL|PostgreSQLDriver|
|SQLite|SQLiteDriver|
|FluentMySQL|FluentMySQL|
|FluentPostgreSQL|FluentPostgreSQL|
|FluentSQLite|FluentSQLite|

**Comment by tanner0101** [comment]
> I might be missing something, do those "integration packages" actually exist, or is there anything that warrants their future existence?

Ah yeah, seems that was only discussed in Discord. The current problem is that the `MySQL` and `PostgreSQL` packages are a little too big and IMO the NIO layer is too coupled with the arguably opinionated vapor/sql query building stuff. 

The NIO layer itself for both MySQL and PostgreSQL are giant and complex and really deserve their own repo. The NIO drivers are also really useful on their own and I'd hate for someone to not use them because they don't want to opt in to the vapor/sql stuff.

**Comment by tanner0101** [comment]
My current favorites for the new name are:

|current|"kit" names|solar system names|
|-|-|-|
|SQL|SQLKit|Star|
|PostgreSQL|PostgreSQLKit|Neptune|
|MySQL|MySQLKit|Mercury|
|SQLite|SQLiteKit|Pluto|
|(new package)|NIOPostgreSQL|NIOPostgreSQL|
|(new package)|NIOMySQL|NIOMySQL|
|(new package)|NIOSQLite|NIOSQLite|

`(new package)` refers to the new packages that will be created when the NIO-specific code is moved into its own package next release. This will be part of the Server Working Group stuff.

**Comment by clayellis** [comment]
+1 for the Kit names. Quirky names do nothing but make it more difficult to understand how things are put together under the hood.

**Comment by MartinLasek** [comment]
### I'd definitely prefer `Kit`
It even fits in the words *meaning* which makes the whole thing feel more natural than f.e. StarSQL.

### Consistency
Especially because it stays *consistent* along all packages in regards of the "added name".

### Easier to spot
It creates a group. Let's say I have `PostgreSQLKit` and want to switch to MySQL, I would pretty fast figure that `MySQLKit` is what I look for since **Kit** groups them together.

It's different if I'd have `NeptunePostgreSQL` and look for the equivalent and find `MercuryMySQL` where alongside also `NIOMySQL` exists. All three have different names. Sure you would eventually get that **Mercury** is the one you are looking for, but it's "less" obvious than the **Kit** 😊

**Comment by tanner0101** [comment]
This package has been renamed to `SQLKit` in #45. Thanks for everyone's feedback and help.
