### ISSUE TITLE
Support the IN operator

### ISSUE THREAD

**Issue by grosch** [vapor/sql#33]
Using the SQLSelectBuilder.html it doesn't seem to be possible to do a `WHERE xyz IN (1, 2, 3)` type filter.

**Comment by tanner0101** [comment]
Support for key path + arrays will be added in #35. After this, you'll be able to do something like:

```swift
try conn.select().all().from(Planet.self)
    .where(\Planet.type, .in, [.smallRocky, .gasGiant])
    .all(decoding: Planet.self)
    .wait()
```
