### ISSUE TITLE
`Pointer being freed was not allocated` crash when compiler optimization on

### ISSUE THREAD

**Issue by andrewtheis** [vapor/sql#4]
**Setup**
- macOS X or Ubuntu 16
- Vapor 3
- Run scheme set to Release configuration
- Two models (ex: `Venue` & `Event` where `Event.venue_id == Venue.id`)
- A route with a query similar to this example:
```swift
Event.query(...).all().flatMap { events in
    let venueIds = events.map { $0.venue_id  }.unique()
    Venue.query(...).filter(\.id ~~ venueIds).all() { venues in
        // ...
    }
}
```

**Other Potentially Useful Info**
- `IN` queries on keys other than `\.id` seem to work.
- `Venue.id` and `Event.id` are `Int` type not `uuid`

**Steps**
1. Run app
2. Hit route
3. Observe results

**Workaround**
Disable compiler optimization for SQL and FluentSQL targets.

**Console Error**
`Run(92599,0x7000063d1000) malloc: *** error for object 0x102389860: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug`

**Stack Trace** (let me know if there is a better way to output this)
![screen shot 2018-05-13 at 4 24 26 am](https://user-images.githubusercontent.com/469799/39965800-a9883f98-5665-11e8-8989-dd31b213ba3e.png)
![screen shot 2018-05-13 at 4 24 36 am](https://user-images.githubusercontent.com/469799/39965801-a9977292-5665-11e8-8943-f8324f7f45fd.png)
![screen shot 2018-05-13 at 4 25 06 am](https://user-images.githubusercontent.com/469799/39965802-a9a51b36-5665-11e8-8846-ca9c8faf8e35.png)

**Comment by MrMage** [comment]
This is a long shot, but could you try if using the https://github.com/MrMage/core/tree/queuehandler-sync branch of VaporCore fixes the issue for you?

**Comment by mcdappdev** [comment]
@MrMage your branch didn’t fix it for me

**Comment by MrMage** [comment]
Sorry to hear that. As I said, it was a long shot ;-) Did you try running this with malloc stack traces and/or Thread Sanitizer enabled to find more details where the data race (which I suspect this is) occurs?

**Comment by andrewtheis** [comment]
@tanner0101 Updating to latest Vapor package versions (along with SwiftNIO 1.8) seems to have resolved this crash. My guess is it was a fix on NIO but I'm not sure.

**Comment by MrMage** [comment]
For what it's worth, it appears that I'm having the same issue now.

**Comment by MrMage** [comment]
Update: it appears that with the very latest versions of all Fluent-related dependencies (from `master`), this no longer crashes. @andrewtheis, can you verify this for your?

**Comment by andrewtheis** [comment]
@MrMage @tanner0101 This issue seems to be resolved running all the latest Vapor package versions.
